services:
   packettracer:
     image: profmancusoa/packettracer:8.2.1
     environment:
       DISPLAY: $DISPLAY
     volumes:
       - /tmp/.X11-unix:/tmp/.X11-unix
       - /dev/shm:/dev/shm
       - ${PWD}:/root/pt/saves
     devices:
       - /dev/dri:/dev/dri
     entrypoint: ["packettracer"]
